check vkryl dir empty or missing

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -22,10 +22,10 @@ jobs:
         run: |
           git submodule update --init --recursive
 
-      - name: Debug Submodules
+      - name: List Root Directory
         run: |
-          ls -R vkryl
-          ls -R app/jni/third_party
+          ls -la
+          ls -la vkryl || echo "vkryl dir empty or missing"
 
       - name: Install Dependencies
         run: |
